name: xbank
services:
  frontend:
    container_name: xbank-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:80"
    networks:
      - shared-network
      - xbank-network-internal
    environment:
      - NODE_ENV=production

networks:
  shared-network:
    external: true
  xbank-network-internal:
    driver: bridge
